name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: gh release view --json assets
      - run: echo hello > hello.txt
      - run: gh release delete-asset ergerg -y
      - run: gh release upload ergerg hello.txt
